=== vini-pietro/DE---T2./HMDCRecords.dtd
<!ELEMENT HMDCRecords (Record+)>
<!ELEMENT Record (client_identifier, principal_diagnosis, Admission, Separation)>
<!ELEMENT client_identifier (#PCDATA)>
<!ELEMENT principal_diagnosis (#PCDATA)>
<!ELEMENT Admission (account_number, admission_date, admission_time, admission_status, ward, clinician_on_admission, specialty_of_clinician_on_admission, intended_length_of_stay, care_type, accommodation_occupied)>
<!ELEMENT account_number (#PCDATA)>
<!ELEMENT admission_date (#PCDATA)>
<!ELEMENT admission_time (#PCDATA)>
<!ELEMENT admission_status (#PCDATA)>
<!ELEMENT ward (#PCDATA)>
<!ELEMENT clinician_on_admission (#PCDATA)>
<!ELEMENT specialty_of_clinician_on_admission (#PCDATA)>
<!ELEMENT intended_length_of_stay (#PCDATA)>
<!ELEMENT care_type (#PCDATA)>
<!ELEMENT accommodation_occupied (#PCDATA)>
<!ELEMENT Surgical_procedure (principal_procedure?,date_of_procedure?,clinician_performing_procedure?)>
<!ELEMENT Separation (separation_date, separation_time, mode_of_separation, clinician_on_separation, specialty_of_clinician_on_separation)>
<!ELEMENT separation_date (#PCDATA)>
<!ELEMENT separation_time (#PCDATA)>
<!ELEMENT mode_of_separation (#PCDATA)>
<!ELEMENT clinician_on_separation (#PCDATA)>
<!ELEMENT specialty_of_clinician_on_separation (#PCDATA)>

=== vini-pietro/DE---T2./HMDCRecords.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HMDCRecords SYSTEM "HMDCRecords.dtd">
<HMDCRecords>
    <Record>
        <client_identifier>P001</client_identifier>
        <principal_diagnosis>Flu</principal_diagnosis>
        <Admission>
            <account_number>AD12345</account_number>
            <admission_date>11/04/2024</admission_date>
            <admission_time>09:30</admission_time>
            <admission_status>4</admission_status>
            <ward>Ward A</ward>
            <clinician_on_admission>Dr. Smith</clinician_on_admission>
            <specialty_of_clinician_on_admission>General Medicine</specialty_of_clinician_on_admission>
            <intended_length_of_stay>1</intended_length_of_stay>
            <care_type>Day Procedure</care_type>
            <accommodation_occupied>Bed</accommodation_occupied>
        </Admission>
        <Separation>
            <separation_date>2024-11-15</separation_date>
            <separation_time>17:00</separation_time>
            <mode_of_separation>1</mode_of_separation>
            <clinician_on_separation>Dr. Smith</clinician_on_separation>
            <specialty_of_clinician_on_separation>General Medicine</specialty_of_clinician_on_separation>
        </Separation>
    </Record>
</HMDCRecords>
