=== vini-pietro/DE---T2./PatientRecords.dtd
<!ELEMENT Patients (Patient+)>
<!ELEMENT Patient (ClientIdentifier, Person, PatientAddress)>
<!ELEMENT ClientIdentifier (#PCDATA)>
<!ELEMENT Person (Client_photo, Client_voice_signature, first_forename, second_forename?, surname, date_of_birth, indigenous_status, country_of_birth, employment_status, marital_status, gender_code, language, Medicare)>
<!ELEMENT Client_photo (#PCDATA)>
<!ELEMENT Client_voice_signature (#PCDATA)>
<!ELEMENT first_forename (#PCDATA)>
<!ELEMENT SecondForename (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT date_of_birth (#PCDATA)>
<!ELEMENT indigenous_status (#PCDATA)>
<!ELEMENT country_of_birth (#PCDATA)>
<!ELEMENT employment_status (#PCDATA)>
<!ELEMENT marital_status (#PCDATA)>
<!ELEMENT gender_code (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT Medicare (MedicareNumber, medicare_person_number, insurance_status)>
<!ELEMENT MedicareNumber (#PCDATA)>
<!ELEMENT medicare_person_number (#PCDATA)>
<!ELEMENT insurance_status (#PCDATA)>
<!ELEMENT PatientAddress (residential_address, postcode, state_or_territory)>
<!ELEMENT residential_address (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT state_or_territory (#PCDATA)>

=== vini-pietro/DE---T2./PatientRecords.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Patients SYSTEM "PatientRecords.dtd">
<Patients>
    <Patient>
        <ClientIdentifier>P001</ClientIdentifier>
        <Person>
            <Client_photo>https://oxclinic.lakesmedical.com.au/DFIOPC58H8</Client_photo>
            <Client_voice_signature>https://oxclinic.lakesmedical.com.au/DFIOPC58H8</Client_voice_signature>
            <first_forename>John</first_forename>
            <surname>Doe</surname>
            <date_of_birth>1988-05-15</date_of_birth>
            <indigenous_status>Non-Aboriginal</indigenous_status>
            <country_of_birth>Western Australia</country_of_birth>
            <employment_status>3</employment_status>
            <marital_status>5</marital_status>
            <gender_code>1</gender_code>
            <language>English</language>
            <Medicare>
                <MedicareNumber>1234567890</MedicareNumber>
                <medicare_person_number>1</medicare_person_number>
                <insurance_status>Insured</insurance_status>
            </Medicare>
        </Person>
        <PatientAddress>
            <residential_address>123 Example Street</residential_address>
            <postcode>6000</postcode>
            <state_or_territory>5</state_or_territory>
        </PatientAddress>
    </Patient>
</Patients>
